# Generated by Django 4.1.7 on 2023-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pic',
            field=models.ImageField(blank=True, default='static/img/userprofile.jpg', null=True, upload_to='pro pic/'),
        ),
    ]
