# Generated by Django 4.1.7 on 2023-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic',
            field=models.ImageField(blank=True, default='static/img/userprofile.jpg', null=True, upload_to='pro_pic/'),
        ),
    ]
