# Generated by Django 4.1.7 on 2023-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userotp_time_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='time_st',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
