# Generated by Django 4.1.7 on 2023-03-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_coupon_alter_cart_coupon'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
