# Generated by Django 4.1.7 on 2023-03-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation',
        ),
    ]
